image: ubuntu:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - docker
  script:
    - echo "🔧 Building Wio Terminal..."
    - export PATH=$PATH:/root/bin
    - pwd
    - cd arduino_src
    - arduino-cli compile --fqbn Seeeduino:samd:seeed_wio_terminal

test:
  stage: test
  script:
    - echo "🧪 Running Wio Terminal tests..."

deploy:
  stage: deploy
  script:
    - echo "🚀 Deploying Wio Terminal..."

