image: node:18

stages:
  - build
  - test
  - deploy

variables:
  NODE_ENV: development

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g eas-cli
  - npm install
  - eas login --token $EXPO_TOKEN

build:
  stage: build
  tags:
    - docker
  script:
    - echo "Building the project..."
    - eas build --platform android --non-interactive

test:
  stage: test
  script:
    - echo "Running tests..."
    # - npm test

deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."


